sonar.projectKey=aceest-fitness-gym-devopsproj
sonar.organization=2024tm93560-eng
sonar.projectName=ACEest Fitness Gym
sonar.projectVersion=2.0.0
sonar.sources=.
sonar.tests=tests
sonar.language=py
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/*.pyc,venv/**,versions/**,reports/**
sonar.sourceEncoding=UTF-8
